
<?php echo $this->doctype()?>
<html>
    <head>
        <?php echo $this->headTitle();?>
	<?php echo $this->headLink();?>
	<?php echo $this->headStyle();?>
	<?php // echo $this->headMeta();?>
   	<?php // echo $this->headScript();?>
    </head>
    <body>
        <div id="conteudo">
                <table class="listagemLink" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Links</th>
                            <th style="width: 30px;">&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->Links as $key => $value) { ?>    
                        <tr>
                            <td><a href="<?php echo $value["LINK"]; ?>" target="_blank"><?php echo $value["DESCRICAO"]; ?></a></td>
                            <td><?php if($this->visualizar){ echo "&nbsp;";}else{
                                ?><img id="<?php echo base64_encode($key); ?>" class="delete-link" alt="Excluir" title="Excluir Link" src="<?php echo PUBLIC_PATH;?>/_img/icones/excluir.png" /><?php
                            } ?>
                            </td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>
        </div>
    </body>
</html>