<div id="lista">
    <div id="lista-borda">
        <div id="lista-titulo">
            <div id="lista-titulo-texto">An&aacute;lise Cargos x Quadros Informativos</div>
            <div id="lista-titulo-menu">
                <div id="lista-titulo-menu-voltar" class="botao" onclick="javascript:OpenSelf('<?php echo $this->baseUrl()?>/admin/informativos/relacionamento');">Voltar</div>
            </div>
        </div>
        <div id="espaco"></div>
        <?php echo base64_decode($this->mensagem);?>
        <div id="formulario">
            <form name="frmCargos" id="frmCargos" method="post" action="<?php echo $this->baseUrl()?>/admin/informativos/relacionamento" enctype="multipart/form-data">
                <label for="cargos">Cargo:</label>
                <select name="selectCargosInformativos" id="selectCargosInformativos">
                    <option value="">Selecione...</option>
                    <?php                
                    foreach($this->cargos as $cargos):
                    ?>
                        <option value="<?php echo $cargos['COD_FUNCAO']; ?>"><?php echo $cargos['DESCR_FUNCAO'];?></option>
                    <?php
                    endforeach;
                    ?>
                </select>
                <br /><br />
                <div id="targetAjaxProc"></div>
                <br /><br />
                <input type="submit" class="inputBtnSalvar" name="btnSalvar" id="btnSalvar" value="Salvar" />
            </form>
        </div>
    </div>
</div>