<div id="lista">
    <div id="lista-borda">
        <div id="lista-titulo">
            <div id="lista-titulo-texto">Editar - <?php echo $this->informativo; ?></div>
            <div id="lista-titulo-menu">
                <div id="lista-titulo-menu-voltar" class="botao" onclick="javascript:OpenSelf('<?php echo $this->baseUrl().'/admin/informativos/itens/id/'.base64_encode($this->id_informativo);?>');">Voltar</div>
            </div>
        </div>
        <div id="espaco"></div>
        <?php echo base64_decode($this->mensagem);?>
        <div id="formulario">
            <?php echo $this->formulario?>
        </div>
    </div>
</div>  