<div id="div_transportadoras">
    <br/><br/>
    <label id="lbl-comprador">Transportadora:</label>
    <select id="transportadora" name="transportadora">
        <option value="">Selecione a Transportadora...</option>
        <?php
        foreach ($this->transportadoras as $transportadora) {
            ?><option value="<?php echo $transportadora["CODIGO_FORNEC"]; ?>" ><?php echo $transportadora["NOME_FORNEC"]; ?></option><?php
        }
        ?>
    </select>
    <br/><br/>
    <label id="lbl-frete">Cotar frete??</label>
    <select name="frete" id="frete">
        <option value="N" selected="selected">Não</option>
        <option value="S">Sim</option>
    </select>
</div>
<div id="msgTransportadora"></div>