<?php 
$Helper_mascaras = new Commit_Controller_Action_Helper_Mascaras(); 

$Entrega = $this->Entrega;
$Prazo = $this->Prazo;
$Fornecedor = $this->Fornecedor;
$Transportadora = $this->Transportadora;
$Empresa = $this->Empresa;
$EmpresaCobranca = $this->EmpresaCobranca;
$Pedido = $this->Pedido;
$itens_pedido = $this->itens_pedido;

ini_set('max_execution_time', '120');
ob_start();

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
<!--        <link href="<?php echo PUBLIC_PATH; ?>_img/logo/usina_impressao.ico" rel="shortcut icon" type="image/x-icon" />       
        <link href="<?php echo PUBLIC_PATH; ?>_css/layout.css"  media="screen" rel="stylesheet" type="text/css" />       
        <link href="<?php echo PUBLIC_PATH; ?>_css/default.css"  media="screen" rel="stylesheet" type="text/css" />   -->
        <style type="text/css">
            table {
                border-spacing: 5px;
            }
        </style>
    </head>
    <body style="width: 738px; margin: 0px auto; font: 10px Verdana,Arial,Helvetica,sans-serif ;font-weight:normal;  border: 0px;">
        <table style="width: 100%;" cellpadding="0" cellspacing="0">
            <tr>
                <td style="border: 1px solid #000;">
                    <table border="0" style="width: 100%" >
                        <tr>
                            <td colspan="6"><?php echo $Empresa["NOME_EMPRESA"]; ?></td>
                            <td rowspan="3">Pedido de Compra Número: <?php echo $Pedido["PEDIDO"]; ?></td>
                        </tr>
                        <tr>
                            <td style="width: 100px;" rowspan="5" ><img src="<?php echo PUBLIC_PATH; ?>_img/logo/usina_impressao.png" style="height: 40px;" /></td>
                        </tr>
                        <tr>
                            <td colspan="3">CNPJ: <?php echo $Empresa["CNPJ_CPF"]; ?></td>
                            <td colspan="2">Incrição Estadual: <?php echo $Empresa["INSCR_EST"]; ?></td>
<!--                            <td>Número: <?php echo $Pedido["PEDIDO"]; ?></td>-->
                        </tr>
                        <tr>
                            <td colspan="3">Ender: <?php echo $Empresa["ENDERECO"] . ", " . $Empresa["NRO"]; ?></td>
                            <td colspan="2">Bairro: <?php echo $Empresa["BAIRRO"]; ?></td>
<!--                            <td>Folha: 2</td>-->
                        </tr>
                        <tr>
                            <td colspan="2">Cidade: <?php echo $Empresa["CIDADE"]; ?></td>
                            <td>Estado: <?php echo $Empresa["ESTADO"]; ?></td>
                            <td>CEP: <?php echo $Empresa["CEP"]; ?></td>
                            <td>Pais: <?php echo $Empresa["PAIS"]; ?></td>
                            <td>Data: <?php echo $Pedido["DT_PEDIDO"]; ?></td>
                        </tr>
                        <tr>
                            <td>Fone: <?php echo $Empresa["FONE"]; ?></td>
                            <td colspan="2">Fax: <?php echo $Empresa["FAX"]; ?></td>
                            <td colspan="3">Email: <?php echo $Empresa["EMAIL"]; ?></td>
                        </tr>
                        <tr>
                            <td colspan="6">COMF0011/COMR0002</td>
                            <td>&nbsp;</td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                <td style="border: 1px solid #000;">
                    <table border="0" style="width: 100%">
                        <tr>
                            <td style="width: 80px;">Fornecedor:</td>
                            <td colspan="4"><?php echo $Fornecedor["NOME_FORNEC"]; ?></td>
                            <td>Código: <?php echo $Fornecedor["CODIGO_FORNEC"]; ?></td>
                        </tr>
                        <tr>
                            <td>Endereço:</td>
                            <td style="width: 300px;"><?php echo $Fornecedor["ENDERECO"] . ", " . $Fornecedor["NRO"]; ?></td>
                            <td style="width: 50px;">Bairro:</td>
                            <td colspan="2"><?php echo $Fornecedor["BAIRRO"]; ?></td>
                            <td>Cep: <?php echo $Fornecedor["CEP"]; ?></td>
                        </tr>
                        <tr>
                            <td>Cidade:</td>
                            <td><?php echo $Fornecedor["CIDADE"]; ?></td>
                            <td>Estado:</td>
                            <td style="width: 120px;"><?php echo $Fornecedor["ESTADO"]; ?></td>
                            <td colspan="2">Pais: <?php echo $Fornecedor["PAIS"]; ?></td>
<!--                            <td>&nbsp;</td>-->
                        </tr>
                        <tr>
                            <td>Fone:</td>
                            <td><?php echo $Fornecedor["FONE"]; ?></td>
                            <td>Fax:</td>
                            <td colspan="3"><?php echo $Fornecedor["FAX"]; ?></td>
                        </tr>
                        <tr>
                            <td>CNPJ:</td>
                            <td><?php echo $Fornecedor["CNPJ_CPF"]; ?></td>
                            <td colspan="4">Incrição Estadual: <?php echo $Fornecedor["INSCR_EST"]; ?></td>
                        </tr>
                        <tr>
                            <td>Contato:</td>
                            <td><?php echo $Pedido["CONTAT_FORN"]; ?></td>
                            <td>Email:</td>
                            <td colspan="3"><?php echo $Fornecedor["EMAIL"]; ?></td>
                        </tr>
                    </table>
                </td>
            </tr>
            <?php if($Transportadora){ ?>
            <tr>
                <td style="border: 1px solid #000;">
                    <table border="0" style="width: 100%">
                        <tr>
                            <td style="width: 80px;">Transportadora:</td>
                            <td colspan="4"><?php echo $Transportadora["NOME_FORNEC"]; ?></td>
                            <td>Código: <?php echo $Transportadora["CODIGO_FORNEC"]; ?></td>
                        </tr>
                        <tr>
                            <td>Endereço:</td>
                            <td style="width: 300px;"><?php echo $Transportadora["ENDERECO"] . ", " . $Transportadora["NRO"]; ?></td>
                            <td style="width: 50px;">Bairro:</td>
                            <td colspan="2"><?php echo $Transportadora["BAIRRO"]; ?></td>
                            <td>Cep: <?php echo $Transportadora["CEP"]; ?></td>
                        </tr>
                        <tr>
                            <td>Cidade:</td>
                            <td><?php echo $Transportadora["CIDADE"]; ?></td>
                            <td>Estado:</td>
                            <td style="width: 120px;"><?php echo $Transportadora["ESTADO"]; ?></td>
                            <td colspan="2">Pais: <?php echo $Transportadora["PAIS"]; ?></td>
<!--                            <td>&nbsp;</td>-->
                        </tr>
                        <tr>
                            <td>Fone:</td>
                            <td><?php echo $Transportadora["FONE"]; ?></td>
                            <td>Fax:</td>
                            <td colspan="3"><?php echo $Transportadora["FAX"]; ?></td>
                        </tr>
                        <tr>
                            <td>CNPJ:</td>
                            <td><?php echo $Transportadora["CNPJ_CPF"]; ?></td>
                            <td colspan="4">Incrição Estadual: <?php echo $Transportadora["INSCR_EST"]; ?></td>
                        </tr>
                        <tr>
                            <td>Contato:</td>
                            <td><?php echo $Pedido["CONTAT_FORN"]; ?></td>
                            <td>Email:</td>
                            <td colspan="3"><?php echo $Transportadora["EMAIL"]; ?></td>
                        </tr>
                    </table>
                </td>
            </tr>
            
            <?php } ?>
            <tr>
                <td style="border: 1px solid #000;">
                    <table border="0" style="width: 100%">
                        <tr>
                            <td style="width: 145px;">Endereço p/ cobrança:</td>
                            <td colspan="2"><?php echo $EmpresaCobranca["ENDERECO"] . ", " . $EmpresaCobranca["NRO"]; ?></td>
                            <td>CEP: <?php echo $EmpresaCobranca["CEP"]; ?></td>
                        </tr>
                        <tr>
                            <td>Cidade:</td>
                            <td><?php echo $EmpresaCobranca["CIDADE"]; ?></td>
                            <td>Estado: <?php echo $EmpresaCobranca["ESTADO"]; ?></td>
                            <td>Pais: <?php echo $EmpresaCobranca["PAIS"]; ?></td>
                        </tr>
                        <tr>
                            <td>Endereço p/ entrega:</td>
                            <td colspan="3"><?php echo $Entrega["LOCAL_ENTREG"]; ?></td>
                        </tr>
                        <tr>
                            <td>Comprador:</td>
                            <td colspan="3"><?php echo $Pedido["NOME_COMPRADOR"]; ?></td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                <td style="border: 1px solid #000;">
                    <table border="0" style="width: 100%">
                        <tr>
                            <td rowspan="<?php echo count($Prazo) + 1; ?>" style="width: 180px;vertical-align:top; ">Condição de Pagamento:</td>
                        </tr>
                        <?php foreach ($Prazo as $prazo) { ?>
                            <tr>
                                <td><?php echo $Helper_mascaras->ValorMoeda($prazo["PERC_PARC"],1); ?> %</td>
                                <td><?php echo $prazo["CONDICAO_PAGAMENTO"]; ?></td>
                            </tr>
                        <?php } ?>
                        <tr>
                            <td colspan="3">Moeda:REAL</td>
                        </tr>
                    </table>
                </td>
            </tr>
<!--            <tr>
                <td style="border: 1px solid #000;">
                    
                </td>
            </tr>
            <tr>
                <td style="border: 1px solid #000;">
                    
                </td>
            </tr>
            <tr>
                <td>
                    <?php echo nl2br($Pedido["OBS_PEDIDO"]); ?>
                </td>
            </tr>-->
<!--            <tr>
                <td>
                    <div id="div-confirmar">
                        <h1>Observação do Fornecedor</h1><br/><br/>
                        <?php if (!$this->post && is_null($this->auth) && !is_null($this->PedidoHistorico)) { ?>

                        <label class="lbl-info_pedido">&nbsp;</label>
                            <form action="" method="POST">
                                <textarea name="observacao" id="textarea-confirmar"><?php echo $this->observacao; ?></textarea><br/>
                                <input name="pedido" type="hidden" value="<?php echo $this->id_pedido; ?>" />
                                <input id="btn-confirmar" type="submit" class="botao" value="Enviar" />
                            </form>
                            <?php
                        } elseif($this->post) {
                            echo $this->mensagem;
                        }elseif($this->observacao){
                            echo nl2br($this->observacao);
                        }else{
                            echo "&nbsp;";
                        }
                        ?>
                    </div>
                </td>
            </tr>-->
        </table>
        
        <table class="largura_100" style="width:100%;border: 1px solid #000;margin: 0px 5px 2px 5px;" cellspacing="0">
                        <thead>
                            <tr style="text-align: left;">
                                <th>Ord.</th>
                                <th style="text-align: center;">Código</th>
                                <th style="text-align: left;">Especificações</th>
                                <th style="text-align: center;">Unid.</th>
                                <th style="text-align: center;">Dt. Entrega</th>
                                <th style="text-align: right;">Quantidade</th>
                                <th style="text-align: right;">Preço unitário</th>
                                <th style="text-align: right;">Valor Total</th>
                                <th style="text-align: right;">%IPI</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($itens_pedido as $key => $item) { ?>
                                <tr style="height: 30px;">
                                    <td style="text-align: right;width: 20px;"><?php echo $key + 1; ?></td>
                                    <td style="text-align: center;"><?php echo $item["COD_PRODUTO"]; ?></td>
                                    <td>&nbsp;</td>
                                    <td style="text-align: center;"><?php echo $item["UNIDADE"]; ?></td>
                                    <td style="text-align: center;"><?php echo $item["PRAZO_ENTREGA"]; ?></td>
                                    <td style="text-align: right;"><?php echo $item["QTDE"]; ?></td>
                                    <td style="text-align: right;"><?php echo $Helper_mascaras->ValorMoeda($item["PRECO_UNIT"],1); ?></td>
                                    <td style="text-align: right;"><?php echo $Helper_mascaras->ValorMoeda($item["VALOR_TOTAL_ITEM"],1); ?></td>
                                    <td style="text-align: right;"><?php echo $Helper_mascaras->ValorMoeda($item["PERC_IPI"],1); ?></td>
                                </tr>
                                <tr>
                                    <td colspan="2">Descrição:</td>
                                    <td colspan="7"><?php echo $item["DESCR_PRODUTO"]; ?></td>
                                </tr>
                                <tr>
                                    <td colspan="2">Classificação:</td>
                                    <td colspan="3"><?php echo $item["CLASSIFICAO"]; ?></td>
                                    <td colspan="4">Embalagem: <?php echo $item["EMBALAGEM"]; ?></td>
                                </tr>
                                <tr>
                                    <td colspan="2">Marca:</td>
                                    <td colspan="7"><?php echo $item["MARCA"]; ?></td>
                                </tr>
                                <tr>
                                    <td colspan="2">Obs.:</td>
                                    <td colspan="7"><?php echo $item["OBS_ITEM"]; ?></td>
                                </tr>
                                <tr><td colspan="9">&nbsp;</td></tr>
                            <?php } ?>
                        </tbody>
                    </table>
                    <table  style="width: 100%;text-align: right;border: 1px solid #000;margin: 5px 5px 5px 5px;">
                        <tr>
                            <td>ENCARGOS FINANC.</td>
                            <td>VALOR DO FRETE</td>
                            <td>VALOR DO IPI</td>
                            <td>OUTRAS DESPESAS</td>
                            <td>TOTAL DO PEDIDO</td>
                        </tr>
                        <tr>                            
                            <td><?php echo $Helper_mascaras->ValorMoeda($Pedido["PERC_ENCARG_FINANC"],1); ?></td>
                            <td><?php echo $Helper_mascaras->ValorMoeda($Pedido["VL_FRETE"],1); ?></td>
                            <td><?php echo $Helper_mascaras->ValorMoeda($Pedido["IPI_INCL_PRECO"],1); ?></td>
                            <td><?php echo $Helper_mascaras->ValorMoeda($Pedido["OUTRAS_DESP_ACESS"],1); ?></td>
                            <td><?php echo $Helper_mascaras->ValorMoeda($Pedido["VALOR"],1); ?></td>
                        </tr>

                    </table>
        <?php if($this->observacao_comprador){ ?>
                    <table  style="width: 100%;text-align: left;border: 1px solid #000;margin: 5px 5px 5px 5px;">
                        <tr>
                            <td>
                                <b>Observação do Comprador</b>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <?php echo nl2br($this->observacao_comprador); ?>
                            </td>
                        </tr>
                    </table>
            <?php } ?>        
        <div style="margin: 2px 5px 2px 5px;"><?php echo nl2br($Pedido["OBS_PEDIDO"]); ?></div>
    </body>
</html>


<?php
//exit;
$content = ob_get_clean();

require_once("dompdf/dompdf_config.inc.php");

$nome_pdf = $Pedido["PEDIDO"] . '.pdf';

$dompdf = new DOMPDF();
$dompdf->load_html(utf8_decode($content));
$dompdf->render();
$dompdf->stream($nome_pdf);


