<div id="lista">
    <div id="lista-borda">
        <div id="lista-titulo">
            <div id="lista-titulo-texto">Cadastro de Processos</div>
            <div id="lista-titulo-menu">
                <div id="lista-titulo-menu-voltar" class="botao" onclick="javascript:OpenSelf('<?php echo $this->baseUrl()?>/admin/processos/');">Voltar</div>
            </div>
        </div>
        <div id="espaco"></div>
        <?php echo base64_decode($this->mensagem);?>
        <div id="formulario">
            <?php echo $this->formulario?>
        </div>
    </div>
</div>