<form action="<?php echo $this->escape($this->element->getAction());?>" 
      method="<?php echo $this->escape($this->element->getMethod());?>" 
      id="<?php echo $this->escape($this->element->getAttrib('id'));?>"  
      class="<?php echo $this->escape($this->element->getAttrib('class'));?>"
      enctype="multipart/form-data">
    <label for="arquivo"><?php echo ($this->element->arquivo);?></label><br />
    <label for="submeter"><?php echo ($this->element->submeter);?></label><br />
    <?php echo ($this->element->id_cargo);?>
    <?php echo ($this->element->id_processo);?>
</form>