<form action="<?php echo $this->escape($this->element->getAction());?>" method="<?php echo $this->escape($this->element->getMethod());?>" id="<?php echo $this->escape($this->element->getAttrib('id'));?>"  class="<?php echo $this->escape($this->element->getAttrib('class'));?>">
    <table cellpadding="0" cellspacing="0" border="0" style="width: 950px;float: right;">
        <tr>
            <td><?php echo ($this->element->de_ci);?></td>
            <td><?php echo ($this->element->ate_ci);?></td>
            <td><?php echo ($this->element->data);?></td>
            <td><?php echo ($this->element->ccusto_de);?></td>
            <td><?php echo ($this->element->ccusto_para);?></td>
            <td><?php echo ($this->element->finalidade);?></td>
            <td><?php echo ($this->element->gerar_xls);?></td>
            <td><?php echo ($this->element->status);?></td>
            <td><?php echo ($this->element->btnPesquisar);?></td>
        </tr>
    </table>
</form>
