<form action="<?php echo $this->escape($this->element->getAction());?>" method="<?php echo $this->escape($this->element->getMethod());?>" id="<?php echo $this->escape($this->element->getAttrib('id'));?>"  class="<?php echo $this->escape($this->element->getAttrib('class'));?>">
    <table cellpadding="0" cellspacing="0" border="0" style="width: 700px;float: right;">
        <tr>
            <td><?php echo ($this->element->data);?></td>
            <td style="width: 300px;"><?php echo ($this->element->login);?></td>
            <td><?php echo ($this->element->btnPesquisar);?></td>
        </tr>
    </table>
</form>
