
<form action="<?php echo $this->escape($this->element->getAction());?>" method="<?php echo $this->escape($this->element->getMethod());?>" id="<?php echo $this->escape($this->element->getAttrib('id'));?>"  class="<?php echo $this->escape($this->element->getAttrib('class'));?>">
    <table cellpadding="0" cellspacing="0" border="0">
        <tr>
            <td colspan="3" ><?php echo ($this->element->nome);?></td>
        </tr>
        <tr>
            <td colspan="3" style="height: 10px;"></td>
        </tr>            
        <tr>
            <td width="250"><?php echo ($this->element->email);?></td>
            <td colspan="2"><?php echo ($this->element->celular);?></td>
        </tr>
        <tr>
            <td colspan="3" style="height: 10px;"></td>
        </tr>            
        <tr>
            <td  width="250"><?php echo ($this->element->login);?></td>
            <td  width="200"><?php echo ($this->element->senha);?></td>
            <td><?php echo ($this->element->status);?></td>
        </tr>
        <tr>
            <td colspan="3" align="right">
                <?php echo ($this->element->submeter);?>
                <?php echo ($this->element->id);?>
            </td>
        </tr>
        <tr>
            <td colspan="3"><span class="hint">* Caso Status Inativo o usuário não terá acesso ao sistema</span></td>
        </tr>
    </table>
</form>

<?php echo $this->element->status->getDescription();?>
 