<?php echo $this->doctype() ?>
<?php
//$sessao = $this->sessao;
// Determina que o arquivo é uma planilha do Excel
header("Content-type: application/vnd.ms-excel");

// Força o download do arquivo
header("Content-type: application/force-download");

// Seta o nome do arquivo
header("Content-Disposition: attachment; filename=relatorio.xls");

header("Pragma: no-cache");

// Imprime o conteúdo da nossa tabela no arquivo que será gerado
?>
<html>
    <head>
        <?php // echo $this->headTitle(); ?>
        <?php // echo $this->headLink(); ?>
        <?php // echo $this->headStyle(); ?>
        <?php  echo $this->headMeta(); ?>
        <?php // echo $this->headScript(); ?>
        <style  type="text/css">
            <?php 
            foreach ($this->headLink() as $value) {
                $valor = get_object_vars($value);
                if($valor["type"]=="text/css"){
                    $result=file_get_contents($valor["href"]);
                    echo $result;
                }
            }
            ?>
        </style>
        <!--Alterações Relatório-->
        <style type="text/css" >
            #Paginador{
                /*display: none;*/
                visibility: hidden;
            }
            #pesquisa-ci{
                /*display: none;*/
                visibility: hidden;
            }
            #lista-titulo{
                /*display: none;*/
                visibility: hidden;
            }            
            .linha-menu img{
                /*display: none;*/
                visibility: hidden;
            }
            
        </style>
    </head>
    <body>
        <table>
            <tr>
                <td><div id="conteudo"><?php echo $this->layout()->content ?></div></td>
            </tr>
        </table>
    </body>
</html>
