<div id="lista">
    <div id="lista-borda">
        <div id="lista-titulo">
            <div id="lista-titulo-texto">Cadastro de C.I.</div>
        </div>
        <div id="espaco"></div>
        <?php echo base64_decode($this->mensagem);?>
        <div id="gride">            
            <br/>
            <div id="formulario">
                <?php echo $this->formulario?>
            </div>            
        </div>
    </div>
</div>


