<?php
echo $this->doctype();
$CI = $this->CI;
$Helper_mascaras = new Commit_Controller_Action_Helper_Mascaras();
?>
<html>
    <head>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php // echo $this->headMeta();?>
<?php // echo $this->headScript(); ?>
    </head>
    <body>
        <div id="conteudo">
            <table id="detalhes-ci" cellpadding="0" cellspacing="0" border="0">
                <tr>
                    <td><b>N° CI:</b><br/><?php echo $CI["ID"]; ?></td>
                    <td><b>EMPRESA:</b><br/><?php echo $CI["EMPRESA"]; ?></td>
                    <td><b>DATA:</b><br/><?php echo $CI["DATA"]; ?></td>
                </tr>
                <tr>
                    <td colspan="3" style="height: 10px;"></td>
                </tr>
                <tr>
                    <td colspan="3"><b>DE:</b><br/><?php echo $CI["CCUSTO_DE"]." - ".$CI["CD_CCUSTO_DE"]; ?></td>
                </tr>
                <tr>
                    <td colspan="3" style="height: 10px;"></td>
                </tr>
                <tr>
                    <td colspan="3"><b>PARA:</b><br/><?php echo $CI["CCUSTO_PARA"]." - ".$CI["CD_CCUSTO_PARA"]; ?></td>
                </tr>
                <tr>
                    <td colspan="3" style="height: 10px;"></td>
                </tr>
                <tr>
                    <td colspan="3"><b>FINALIDADE:</b><br/><?php echo $CI["FINALIDADE"]; ?></td>
                </tr>
                <tr>
                    <td colspan="3" style="height: 10px;"></td>
                </tr>
                <tr>
                    <td colspan="3"><b>MOTIVO:</b><br/><?php echo nl2br($CI["MOTIVO_CI"]); ?></td>
                </tr>
                <tr>
                    <td colspan="3" style="height: 20px;"></td>
                </tr>
                <?php
                $total_despesas = 0;
                $total_adiantamentos = 0;
                foreach ($this->despesas as $despesa) {
                    if($despesa["VALOR"] > 0){
                        $achou_despesa = 1;
                        if($despesa["TIPO"] == 1){
                            $total_despesas+= $despesa["VALOR"];
                        }else{
                            $total_adiantamentos+= $despesa["VALOR"];
                        }
                ?>
                    <tr>
                        <td style="text-transform: uppercase;"><b><?php echo ($despesa["DESCRICAO"]); ?>:</b></td>
                        <td colspan="2"><span style="float: left;">R$</span><span style="width:80px;float: left; text-align: right;"><?php echo $Helper_mascaras->ValorMoeda($despesa["VALOR"],1); ?> </span>
                            <!--<span style="float: left;margin-left: 5px;"> ( <?php echo $despesa["TIPO"] == 1 ? "+" : "-" ?> ) </span>-->
                        </td>
                    </tr>
                <?php }} ?>
                <?php if(isset($achou_despesa)){ ?>
                <tr>
                    <td colspan="3" style="height: 30px;"></td>
                </tr>
                <tr>
                    <td style="text-transform: uppercase;"><b>TOTAL DESPESAS:</b></td>
                    <td colspan="2" style="font-weight: bold;"><span style="float: left;">R$</span><span style="width:80px;float: left; text-align: right;"><?php echo $Helper_mascaras->ValorMoeda($total_despesas,1); ?> </span>
                    </td>
                </tr>
                <tr>
                    <td style="text-transform: uppercase;"><b>TOTAL ADIANTAMENTO:</b></td>
                    <td colspan="2" style="font-weight: bold;"><span style="float: left;">R$</span><span style="width:80px;float: left; text-align: right;"><?php echo $Helper_mascaras->ValorMoeda($total_adiantamentos,1); ?> </span>
                        <span style="float: left;margin-left: 5px;"> ( - ) </span>
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td colspan="2" style="height: 10px;float: left;">
                        <hr style="width: 130px;" />
                    </td>
                </tr>
                <?php } ?>
                <tr>
                    <td><b>VALOR<?php if(isset($achou_despesa)){ ?> TOTAL CI<?php } ?>:</b></td>
                    <td colspan="2" style="font-weight: bold;"><span style="float: left;">R$</span><span style="width:80px;float: left; text-align: right;"><?php echo $Helper_mascaras->ValorMoeda($CI['VALOR'],1); ?> </span></td>
                </tr>
                <tr>
                    <td colspan="3" style="height: 20px;"></td>
                </tr>
                <tr>
                    <td colspan="3"><b>NOME DO SOLICITANTE:</b> <?php echo $CI["USUARIO"]; ?></td>
                </tr>
                <tr>
                    <td colspan="3" style="height: 20px;"></td>
                </tr>
                <tr>
                    <td colspan="3"><b>STATUS:</b> <?php echo $CI["STATUS"]; ?></td>
                </tr>
                <?php 
                $motivo_reprovacao = null;
                if(count($this->LogCI)>0){
                    foreach ($this->LogCI as $value1) {
//                        Zend_Debug::dump($value1);
                        if(strlen($value1["MOTIVO_CANCELAMENTO"])>0 && ($value1["ID_STATUS"] == 4 || $value1["ID_STATUS"] == 5)){
                            $motivo_reprovacao = $value1["MOTIVO_CANCELAMENTO"];
                        }
                    }
                } 
                if($motivo_reprovacao && ($CI["ID_STATUS"] == 4 || $CI["ID_STATUS"] == 5)){?>
                <tr>
                    <td colspan="3" style="height: 20px;"></td>
                </tr>
                <tr>
                    <td colspan="3"><b>MOTIVO <?php if($CI["ID_STATUS"] == 5){ ?>CANCELAMENTO:<?php }else{ ?>REPROVA&Ccedil;&Atilde;O:<?php } ?></b><br/><?php echo $motivo_reprovacao; ?></td>
                </tr>
                <?php }  ?>
                <tr>
                    <td colspan="3" style="height: 20px;"></td>
                </tr>
            </table>
            <?php if(count($this->LogCI)>0){ ?>
            <table class="listagemLink">
                <thead>
                    <tr>
                        <th colspan="4" style="border-bottom: 1px solid #EEE;text-align: center;font-size: 13px;font-weight: bold;">Log de Aprovações</th>
                    </tr>
                    <tr>
                        <th>Data</th>
                        <th>Aprovador</th>
                        <th>Observa&ccedil;&atilde;o</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($this->LogCI as $value) { ?>
                    <tr>
                        <td><?php echo $value["DATA"]; ?></td>
                        <td><?php echo $value["APROVADOR"]; ?></td>
                        <td><?php echo $value["MOTIVO_CANCELAMENTO"]; ?></td>
                        <td><?php echo $value["STATUS"]; ?></td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
            <br/>
            <?php } ?>
            <?php if(count($this->Anexos)>0){ ?>
            <table class="listagemLink" cellspacing="0">
    <thead>
        <tr>
            <th colspan="4" style="border-bottom: 1px solid #EEE;text-align: center;font-size: 13px;font-weight: bold;">Anexos</th>
        </tr>
        <tr>
            <th>Arquivo</th>
            <th>Tamanho</th>
            <th style="width: 30px;">&nbsp;</th>
            <th style="width: 30px;">&nbsp;</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($this->Anexos as $key => $value) { ?>    
        <tr>
            <td style="min-width: 300px;"><?php echo $value["DESCRICAO"]; ?></td>
            <td><?php echo $value["TAMANHO"]." KB"; ?></td>
            <td><img id="<?php echo base64_encode($key); ?>" class="download-anexo" alt="Download" title='Baixar "<?php echo $value["NOME_ORIGINAL"]; ?>"' src="<?php echo PUBLIC_PATH;?>/_img/icones/download.png" /></td>
            <td><?php if($this->visualizar){ echo "&nbsp;";}else{
                ?><img id="<?php echo base64_encode($key); ?>" class="delete-anexo" alt="Excluir" title="Excluir Anexo" src="<?php echo PUBLIC_PATH;?>/_img/icones/excluir.png" /><?php
            } ?>
            </td>
        </tr>
    <?php } ?>
    </tbody>
</table>
<form  id="form_download" name="form_download" method="post" enctype='multipart/form-data' action="<?php echo FORM_PATH; ?>admin/ci/download" >
    <input id="anexo" name="anexo" type="hidden" value="" />
</form>

            <?php } ?>
        </div>
    </body>
</html>