<?php
    $menuNamespace  = new Zend_Session_Namespace('PERMISSAO');
    $premissao      = $menuNamespace->_permissao;
    $linkInsert     = (($premissao[0]['INSERIR'] == 't')? "OpenSelf('".$this->baseUrl()."/admin/ci/cadastro');":"alert('Sem permissão');");
    $Helper_mascaras = new Commit_Controller_Action_Helper_Mascaras();
?>
<div id="lista">
    <div id="lista-borda">
        <div id="lista-titulo">
            <div id="lista-titulo-texto">Log Aprovações</div>
            <div id="lista-titulo-menu">
                <div id="lista-titulo-menu-novo" class="botao" onclick="javascript:<?php echo $linkInsert?>">Novo Cadastro</div>
            </div>
        </div>
        <div id="espaco"></div>
        <div id="pesquisa-ci">
            <?php echo $this->form_pesquisa; ?>            
        </div>
        <div id="gride">
            <table class="listagem" cellspacing="0">
                <thead>
                    <tr>
                        <th>N° CI</th>
                        <th>Avalia&ccedil;&atilde;o</th>
                        <th>Aprovador</th>
                        <th>Empresa</th>
                        <th>Centro Custo</th>
                        <th>Finalidade</th>
                        <th>Valor</th>
                        <th>Solicitante</th>
                        <th>Status</th>
                        <th>&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    if(count($this->paginator) > 0):
                        foreach ($this->paginator as $value): ?>
                            <tr class="linha_ci" id="<?php echo base64_encode($value['CI']);?>">
                                <td class="linha"><?php echo $value['CI']?></td>
                                <td class="linha"><?php echo $value['DATA_LOG']?></td>
                                <td class="linha"><?php echo $value['APROVADOR']?></td>
                                <td class="linha"><?php echo $value['EMPRESA']?></td>
                                <td class="linha"><?php echo $value['CCUSTO_PARA']?></td>
                                <td class="linha"><?php echo (strlen($value['FINALIDADE'])>82)?substr($value['FINALIDADE'], 0, 80)."...":$value['FINALIDADE']; ?></td>
                                <td class="linha"><?php echo $Helper_mascaras->ValorMoeda($value['VALOR'],1);?></td>
                                <td class="linha"><?php echo $value['USUARIO']?></td>
                                <td class="linha"><?php echo $value['STATUS']?></td>
                                <td class="linha linha-menu"></td>
                            </tr>
                        <?php 
                        endforeach;
                    else:
                    ?>
                        <tr>
                            <td colspan="10" class='nenhum'>Nenhum Registro encontrado</td>
                        </tr>
                    <?php
                    endif;
                    ?>
                    <tr>
                        <td colspan="10">&nbsp;</td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="10"><?php echo $this->paginator?></td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>