<?php
    $menuNamespace  = new Zend_Session_Namespace('PERMISSAO');
    $premissao      = $menuNamespace->_permissao;
    $linkInsert     = (($premissao[0]['INSERIR'] == 't')? "openModal('".$this->baseUrl()."/admin/ci/insertqtdeaprovadores',500,'auto','Qtde x Aprovadores',null,null,'form-qtdeaprovadores');":"alert('Sem permissão');");   
    $Helper_mascaras = new Commit_Controller_Action_Helper_Mascaras();
?>

<div id="lista">
    <div id="lista-borda">
        <div id="lista-titulo">
            <div id="lista-titulo-texto">Valores x Qtde Aprovadores</div>
            <div id="lista-titulo-menu">
                <div id="lista-titulo-menu-novo" class="botao" onclick="javascript:<?php echo $linkInsert?>">Novo Cadastro</div>
            </div>
        </div>
        <div id="espaco"></div>        
        <div id="gride">
            <table class="listagem" cellspacing="0">
                <thead>
                    <tr>
                        <th>Valor Inicial</th>
                        <th>Valor Final</th>
                        <th>Qtde Aprovadores</th>
                        <th>Emails em cópia</th>
                        <th>Aprovadores</th>
                        <th>&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    if(count($this->paginator) > 0):
                        foreach ($this->paginator as $value):
                            
                            $linkUpdate     = (($premissao[0]['ALTERAR'] == 't')? "openModal('".$this->baseUrl()."/admin/ci/updateqtdeaprovadores/id/". base64_encode($value['ID']) ."',500,'auto','Qtde x Aprovadores',null,null,'form-qtdeaprovadores');":"alert('Sem permissão');");
                            $linkDelete     = (($premissao[0]['EXCLUIR'] == 't')? "confirmaModal('".$this->baseUrl()."/admin/ci/deleteqtdeaprovadores/id/". base64_encode($value['ID']) ."',350,'auto','Deseja realmente apagar o registro?');":"alert('Sem permissão');");
                            ?>
                            <tr itemref="clique">
                                <td class="linha"><?php echo $Helper_mascaras->ValorMoeda($value['VALOR_INICIAL'],1); ?></td>
                                <td class="linha"><?php echo $Helper_mascaras->ValorMoeda($value['VALOR_FINAL'],1); ?></td>
                                <td class="linha"><?php echo $value['APROVADORES']; ?></td>
                                <td class="linha"><?php echo str_replace(";", "<br/>", $value['EMAILCOPIA']); ?></td>
                                <td class="linha">
                                    <?php 
                                    if($value['USUARIOS']){
                                        foreach ($value['USUARIOS'] as $aprovadores) {
                                    ?> <img class="delete_aprovadorgeral" alt="Remover" title='Remover <?php echo $aprovadores['NOME'];?> desta faixa de valor' id="<?php echo base64_encode($aprovadores['ID']) ?>" src="<?php echo PUBLIC_PATH."_img/icones/remover.png"; ?>" /> <?php echo $aprovadores['NOME'];?> <br/><?php
                                        }
                                    }
                                            ?>
                                </td>
                                <td class="linha">
                                    <img class="add_aprovadorgeral" alt="Add Aprovador" title='Adicionar Aprovador a esta faixa de valor' id="<?php echo base64_encode($value['ID']) ?>" src="<?php echo PUBLIC_PATH."_img/icones/add_aprovadorgeral.png"; ?>" />
                                    <img onclick="javascript:<?php echo $linkUpdate?>" src="<?php echo PUBLIC_PATH?>_img/icones/editar.png" border="0" title="Editar os dados desta faixa de valores" />
                                    <img onclick="javascript:<?php echo $linkDelete?>" src="<?php echo PUBLIC_PATH?>_img/icones/excluir.png" border="0"  title="Excluir faixa de valores" />
                                </td>
                            </tr>
                        <?php 
                        endforeach;
                    else:
                    ?>
                        <tr>
                            <td colspan="6" class='nenhum'>Nenhum Registro encontrado</td>
                        </tr>
                    <?php
                    endif;
                    ?>
                    <tr>
                        <td colspan="6">&nbsp;</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>