<div id="lista">
    <div id="lista-borda">
        <div id="lista-titulo">
            <div id="lista-titulo-texto">Altera&ccedil;&atilde;o de C.I. N&#176; <?php echo $this->numero_ci; ?></div>
        </div>
        <div id="espaco"></div>
        <?php echo base64_decode($this->mensagem);?>
        <div id="gride">            
            <br/>
            <div id="formulario">
                <?php echo $this->formulario?>
            </div>            
        </div>
    </div>
</div>
