<div id="lista">
    <div id="lista-borda">
        <div id="lista-titulo">
            <div id="lista-titulo-texto">Cadastro de Hora Extra</div>
            <div id="lista-titulo-menu">
                <div id="lista-titulo-menu-voltar" class="botao" onclick="javascript:OpenSelf('<?php echo $this->baseUrl()?>/admin/eventos/horas');">Voltar</div>
            </div>
        </div>
        <div id="espaco"></div>
        <?php echo base64_decode($this->mensagem);?>
    </div>
</div>