<?php
    $menuNamespace  = new Zend_Session_Namespace('PERMISSAO');
    $premissao      = $menuNamespace->_permissao;
    $linkDigi     = (($premissao[0]['INSERIR'] == 't')? "OpenSelf('".$this->baseUrl()."/admin/eventos/digitacao');":"alert('Sem permissão');");   
    $linkImp      = (($premissao[0]['INSERIR'] == 't')? "OpenSelf('".$this->baseUrl()."/admin/eventos/importacao');":"alert('Sem permissão');");   
?>

<div id="lista">
    <div id="lista-borda">
        <div id="lista-titulo">
            <div id="lista-titulo-texto">Hora Extra</div>
            <div id="lista-titulo-menu">
                <div id="lista-titulo-menu-novo" class="botao" onclick="javascript:<?php echo $linkDigi?>">Digitação</div>
                <div id="lista-titulo-menu-novo" class="botao" onclick="javascript:<?php echo $linkImp?>">Importação</div>
            </div>
        </div>
        <div id="espaco"></div>
        <div id="pesquisa">
            <form method="POST" id="formulario-pesquisa" name="formulario-pesquisa">
                <table>
                    <tr class="titulo">
                        <td>C&oacute;d. Cargo: 
                            <input type="text" name="id_cargo" id="id_cargo" value="<?php echo $this->id_cargo?>" /></td>
                        <td>Centro de Custo:
                            <input type="text" name="cd_ccusto" id="cd_ccusto" value="<?php echo $this->cd_ccusto?>" />                            
                        </td>
                        <td><input type="submit" name="btnPesquisar" value="Pesquisar" class="inputBtnPesquisar" /></td>
                    </tr>
                </table>
            </form>
        </div>
        <div id="gride">
            <table class="listagem" cellspacing="0">
                <thead>
                    <tr>
                        <th>C&oacute;d. Cargo</th>
                        <th>Centro de Custo</th>
                        <th>M&ecirc;s Ref.</th>
                        <th>QTD</th>
                        <th>Menu</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    if(count($this->paginator) > 0):
                        foreach ($this->paginator as $value):
                            
                            $linkUpdate     = (($premissao[0]['ALTERAR'] == 't')? "OpenSelf('".$this->baseUrl()."/admin/eventos/update/id/". base64_encode($value['ID']) ."');":"alert('Sem permissão');");
                            $linkDelete     = (($premissao[0]['EXCLUIR'] == 't')? "if(confirm('Deseja realmente apagar o registro?')) {OpenSelf('".$this->baseUrl()."/admin/eventos/delete/id/". base64_encode($value['ID']) ."');}":"alert('Sem permissão');");
                            ?>
                            <tr itemref="clique">
                                <td class="linha"><?php echo $value['COD_FUNCAO']?></td>
                                <td class="linha"><?php echo $value['CD_CCUSTO']?> - <?php echo $value['NOME_CCUSTO']?></td>
                                <td class="linha"><?php echo $value['MES']?></td>
                                <td class="linha"><?php echo $value['QUANTIDADE']?></td>
                                <td class="linha">
                                    <img onclick="javascript:<?php echo $linkUpdate?>" src="<?php echo PUBLIC_PATH?>_img/icones/editar.png" border="0" title="Editar os dados do processo" />
                                    <img onclick="javascript:<?php echo $linkDelete?>" src="<?php echo PUBLIC_PATH?>_img/icones/excluir.png" border="0"  title="Excluir o processo" />
                                </td>
                            </tr>
                        <?php 
                        endforeach;
                    else:
                    ?>
                        <tr>
                            <td colspan="5" class='nenhum'>Nenhum Registro encontrado</td>
                        </tr>
                    <?php
                    endif;
                    ?>
                    <tr>
                        <td colspan="5">&nbsp;</td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="5"><?php echo $this->paginator?></td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>