<div id="gride">
    <form name="frmRel" method="post" action="" id="frmRel">
        <fieldset class='rel'>
            <legend>Horas Extras</legend>
            <label>Relat&oacute;rio: </label>
            <select name="selectRel" id="selectRel">
                <option value="">Selecione...</option>
                <option value="1">Funcion&aacute;rio</option>
                <option value="2">Cargo</option>
            </select>
            <br /><br />
            <label>Data Ref.:</label>
            <input type="text" name="mes_ref" id="mes_ref" size="10" maxlength="10" />
            <br /><br />
            <input type="submit" name="btnSubmit" id="btnSubmit" class="botao" />
        </fieldset>
    </form>
    
    
    <div id="targetAjax"></div>
    
</div>
