<div id="lista">
    <div id="lista-borda">
        <div id="lista-titulo">
            <div id="lista-titulo-texto">Pesquisa Log Acesso</div>            
        </div>
        <div id="espaco"></div>
        <div id="pesquisa">
            <?php echo $this->form_pesquisa; ?>
        </div>
        <div id="gride">
            <table class="listagem" cellspacing="0">
                <thead>
                    <tr>
                        <th>C&oacute;digo</th>
                        <th>Login</th>
                        <th>Data Login</th>
                        <th>Data Logout</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    if(count($this->paginator) > 0):
                        foreach ($this->paginator as $value):                            
                            ?>
                            <tr itemref="clique">
                                <td class="linha"><?php echo $value['CODIGO']?></td>
                                <td class="linha"><?php echo $value['LOGIN']?></td>
                                <td class="linha"><?php echo $value['DATA_LOGIN']?></td>
                                <td class="linha"><?php echo $value['DATA_LOGOUT']?></td>
                            </tr>
                        <?php 
                        endforeach;
                    else:
                    ?>
                        <tr>
                            <td colspan="4" class='nenhum'>Nenhum Registro encontrado</td>
                        </tr>
                    <?php
                    endif;
                    ?>
                    <tr>
                        <td colspan="4">&nbsp;</td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="4"><?php echo $this->paginator?></td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>